[2021-06-24 16:23:45,317] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 16:23:45,325] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 16:23:45,325] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 16:23:45,325] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-24 16:23:45,325] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 16:23:45,352] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-01-11T00:00:00+00:00
[2021-06-24 16:23:45,354] {standard_task_runner.py:52} INFO - Started process 2208 to run task
[2021-06-24 16:23:45,360] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-01-11T00:00:00+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpcwc1o95s', '--error-file', '/tmp/tmp7tsq3p39']
[2021-06-24 16:23:45,361] {standard_task_runner.py:77} INFO - Job 78: Subtask task_1
[2021-06-24 16:23:45,445] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [running]> on host airflowvm
[2021-06-24 16:23:45,570] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-11T00:00:00+00:00
[2021-06-24 16:23:45,574] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-24 16:23:45,575] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-24 16:23:45,584] {subprocess.py:75} INFO - Output:
[2021-06-24 16:23:48,593] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-24 16:23:48,620] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200111T000000, start_date=20210624T162345, end_date=20210624T162348
[2021-06-24 16:23:48,658] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-06-24 16:23:48,710] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-24 17:03:53,850] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 17:03:54,552] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 17:03:54,573] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:03:54,573] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-24 17:03:54,574] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:03:54,890] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-01-11T00:00:00+00:00
[2021-06-24 17:03:55,058] {standard_task_runner.py:52} INFO - Started process 9082 to run task
[2021-06-24 17:03:55,250] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-01-11T00:00:00+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp_q7d4cdd', '--error-file', '/tmp/tmpxw6f2eah']
[2021-06-24 17:03:55,311] {standard_task_runner.py:77} INFO - Job 19: Subtask task_1
[2021-06-24 17:03:57,155] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-01-11T00:00:00+00:00 [running]> on host airflowvm
[2021-06-24 17:03:58,250] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-11T00:00:00+00:00
[2021-06-24 17:03:58,252] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-24 17:03:58,269] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-24 17:03:58,454] {subprocess.py:75} INFO - Output:
[2021-06-24 17:04:01,486] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-24 17:04:02,551] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200111T000000, start_date=20210624T170353, end_date=20210624T170402
[2021-06-24 17:04:06,549] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-24 17:04:06,766] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-24 17:04:06,847] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 9082
[2021-06-24 17:04:06,900] {process_utils.py:66} INFO - Process psutil.Process(pid=9082, status='terminated', exitcode=0, started='17:03:54') (9082) terminated with exit code 0
