[2021-06-25 09:17:31,442] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-24T00:00:00+00:00 [queued]>
[2021-06-25 09:17:31,499] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-24T00:00:00+00:00 [queued]>
[2021-06-25 09:17:31,500] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:17:31,503] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-25 09:17:31,504] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:17:31,548] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-02-24T00:00:00+00:00
[2021-06-25 09:17:31,576] {standard_task_runner.py:52} INFO - Started process 5036 to run task
[2021-06-25 09:17:31,655] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-02-24T00:00:00+00:00', '--job-id', '212', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpdst_owwr', '--error-file', '/tmp/tmp6cpl0bpl']
[2021-06-25 09:17:31,674] {standard_task_runner.py:77} INFO - Job 212: Subtask task_1
[2021-06-25 09:17:32,235] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-02-24T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:17:32,934] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-02-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-24T00:00:00+00:00
[2021-06-25 09:17:32,959] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:17:32,963] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:17:33,080] {subprocess.py:75} INFO - Output:
[2021-06-25 09:17:36,111] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:17:36,592] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200224T000000, start_date=20210625T091731, end_date=20210625T091736
[2021-06-25 09:17:37,143] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:17:37,313] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-06-25 09:17:37,378] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5036
[2021-06-25 09:17:37,444] {process_utils.py:66} INFO - Process psutil.Process(pid=5036, status='terminated', exitcode=0, started='09:17:30') (5036) terminated with exit code 0
