[2021-06-24 16:24:17,770] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 16:24:17,780] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 16:24:17,781] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 16:24:17,781] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-24 16:24:17,781] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 16:24:17,811] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-01-11T00:00:00+00:00
[2021-06-24 16:24:17,814] {standard_task_runner.py:52} INFO - Started process 2251 to run task
[2021-06-24 16:24:17,819] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-01-11T00:00:00+00:00', '--job-id', '84', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpe06us3b5', '--error-file', '/tmp/tmp_5i7i0ou']
[2021-06-24 16:24:17,821] {standard_task_runner.py:77} INFO - Job 84: Subtask task_3
[2021-06-24 16:24:18,019] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [running]> on host airflowvm
[2021-06-24 16:24:18,212] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-11T00:00:00+00:00
[2021-06-24 16:24:18,213] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-24 16:24:18,214] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-24 16:24:18,223] {subprocess.py:75} INFO - Output:
[2021-06-24 16:24:21,230] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-24 16:24:21,275] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200111T000000, start_date=20210624T162417, end_date=20210624T162421
[2021-06-24 16:24:21,309] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-24 16:24:21,353] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-24 17:04:19,271] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 17:04:19,732] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [queued]>
[2021-06-24 17:04:19,737] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:04:19,737] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-24 17:04:19,739] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:04:20,083] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-01-11T00:00:00+00:00
[2021-06-24 17:04:20,241] {standard_task_runner.py:52} INFO - Started process 9615 to run task
[2021-06-24 17:04:20,460] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-01-11T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpews11djw', '--error-file', '/tmp/tmp4wk7v3as']
[2021-06-24 17:04:20,574] {standard_task_runner.py:77} INFO - Job 34: Subtask task_3
[2021-06-24 17:04:21,890] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-01-11T00:00:00+00:00 [running]> on host airflowvm
[2021-06-24 17:04:23,593] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-01-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-11T00:00:00+00:00
[2021-06-24 17:04:23,597] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-24 17:04:23,598] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-24 17:04:23,906] {subprocess.py:75} INFO - Output:
[2021-06-24 17:04:26,993] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-24 17:04:27,608] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200111T000000, start_date=20210624T170419, end_date=20210624T170427
[2021-06-24 17:04:31,813] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-24 17:04:31,994] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 9615
[2021-06-24 17:04:32,046] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-24 17:04:32,050] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-06-24 17:04:32,199] {process_utils.py:66} INFO - Process psutil.Process(pid=9615, status='terminated', exitcode=1, started='17:04:19') (9615) terminated with exit code 1
